### ISSUE TITLE
How do I update dictionary for file?

### ISSUE THREAD

**Issue by rlam3** [amol-/depot#19]
How do I update dictionary for for my sqlalchemy object?

I keep getting the following message:

```
TypeError: Already saved files are immutable
```

This would prevent me from doing a data migration of the depot. Please advise. Thanks!

**Comment by amol-** [comment]
I'm not sure what do yo mean by "doing a data migration of the depot".
By depot design files are immutable after uploaded, if you want to mutate a file you should upload a new one and delete the old one.

**Comment by rlam3** [comment]
What I mean was to migrate from one depot to a depot with different prefix without having to reupload everything. 

Therefore the dictionary depot_name would have to be updated as well as the values inside the dictionary for the uploadedfilefield. 

Do you know of a way to disable the immutable feature for migrations?

**Comment by amol-** [comment]
Disabling it would practically break anything in database integration, so it's not possible to disable it.
Also you are not required to change the depot_name, you can just change the prefix in the configuration if I understood what you are trying to do.

DEPOT itself doesn't make any assumption regarding the features of the underlying storage, so it doesn't provide a feature to move files without re-uploading them as that is something not all storages might support (E.G. Gridfs doesn't support moving documents between collections without reinserting them). If you are migrating files from a place to another using a Storage specific feature you are on your own also on updating all the DEPOT metadata.

**Comment by rlam3** [comment]
Future reference.

Raw PSQL Steps for replacing specific strings/depots:

````
begin;
update table set field = replace(field,'replace_this_depot_name','with_this_new_depot_name') ;
commit;
````

Migrating from local to s3

1. loop through all folders to rename files in child directories
````
for d in `ls -h`
do
    # echo "$d"
    mv "$d/file" "$d/$d"
    mv "$d/$d" "_prefix/"
````
2.  Use ftp to move all files from _prefix folder on local machine to s3 folder with prefix.
