### ISSUE TITLE
Is there a way for us to reduce the amount of GET requests?

### ISSUE THREAD

**Issue by rlam3** [amol-/depot#20]
Do you think there is a way to optimize how we do GET requests with depot? 

I saw something about LIST as being 0 charge but not sure if it is the same as GET

**Comment by vlcinsky** [comment]
@rlam3 Can you provide a bit more context?

Do you talk about AWS S3? Doing some list operation of data store?

**Comment by rlam3** [comment]
Yes, so instead of doing GET. We do LIST because it cost less than GET

**Comment by vlcinsky** [comment]
@rlam3 There are multiple operation types performed by depot (created, replace, delete, list...).

I checked the implementation briefly and to me it seems implemented properly, e.g. to list items, it uses proper list method of the bucket.

Regarding costs related to AWS S3, my experience is, the highest costs are:
- storage itself
- data transfer out of home region or out of AWS (when moving large amount of data, it can surprise)

Costs related to performing GET and LIST operations (in my case) are always almost negligible comparing to the rest.

Unless you have clear case where the implementation is not efficient, I would propose to close this issue. If you have the case, provide more details.
