### ISSUE TITLE
Is there a way for me to compress the image size so that my page can load faster?

### ISSUE THREAD

**Issue by rlam3** [amol-/depot#23]
Is there a way for me to compress the image size so that my page can load faster? Any image compression tools that I you can recommend for me to do this?

Also, would it be better to mount s3 onto your server instead of using boto and use depot as if it was a local directory?

**Comment by amol-** [comment]
Well, more than compressing (as images are usually already compressed and compressing already compressed data might only make it bigger by adding compression header and metadata twice) you should probably tune the format, quality, size of the image. That can also be done using a DEPOT filter or custom attachment that uses Pillow to re-encode the image at lower quality or with another format.

If you are using DepotMiddleware to serve files from S3 it won't actually serve them, it will just perform and HEAD request to check that they exist and will then redirect the user to S3. That's the behaviour for any storage backend that provides public urls like S3.

If you are using the database layer it won't even perform the HEAD request as it will directly return the public url as the .`url` property of the file.
