### ISSUE TITLE
Size of VARCHAR (4000 bytes) in UploadedFileField type triggers ORA-00910 error in Oracle

### ISSUE THREAD

**Issue by piotr-dobrogost** [amol-/depot#26]
When using depot with Oracle (through Kotti web framework) I'm getting this error
`sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00910: specified length too long for its datatype.`

This is due using size of 4096 bytes for `VARCHAR` type here https://github.com/amol-/depot/blob/0.3.0/depot/fields/sqlalchemy.py#L43

Maximum size of `VARCHAR` in Oracle is [4000 bytes](https://docs.oracle.com/cd/B28359_01/server.111/b28320/limits001.htm)

The solution could be to use generic SQLAlchemy type (`String` in this case?) instead of hardcoding specific type. Compare with similar problem [Generic TEXT/CLOB data type for cross-database SQLAlchemy application](http://stackoverflow.com/q/20378389/95735)

**Comment by amol-** [comment]
Sadly there was a specific reason for this being a VARCHAR, even though I don't remember which one it was. Probably related to Alembic migrations autogeneration. 4096 bytes is actually a random value "big enough to contain json with all metadata". I think It's farily safe to lower its size.
