### ISSUE TITLE
boto3 and therefore minio support

### ISSUE THREAD

**Issue by multiwave** [amol-/depot#28]
For our development environment, I setup minio to simulate S3 storage. But communicating with it using existing depot and boto code was impossible (had to be SSL, needed patch to use custom port, custom s3 authentication mechanism, install CA to verify certs,...)

So I gave up and wrote a layer to work with boto3, I figured I'll share it with you guys. There is one thing missing - encrypt_key support. I don't understand what that's supposed to do in the original code, therefore I have no clue how to migrate that to boto3.

Find the boto3 wrapper attached to this issue:

[depot_minio.py.zip](https://github.com/amol-/depot/files/252662/depot_minio.py.zip)

Here is how I call it 

``` python
DepotManager.configure('s3devel', {'depot.backend': 'depot_minio.MinioStorage',
            'depot.access_key_id': '...',
            'depot.secret_access_key': '....',
            'depot.bucket': 'my-bucket',
            'depot.endpoint': 'http://localhost:9000',
            'depot.prefix': 'my-prefix',
        })
```

I am willing to help integrate this into your project, if you are interested to support boto3 and minio. Just let me know how I can help
br
 mike

**Comment by amol-** [comment]
This is something really interesting and I think it would be valuable to have both boto and boto3 backends in Depot. As Minio is compatible with boto3 I think we should have a S3 storage based on Boto3 and let people use it with Minio. 

Regarding the `encrypt_key` that tells S3 to encrypt the object server side, see http://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.key.Key.set_contents_from_string

Best solution that comes to my mind is provide an `BotoBucketDriver` and `Boto3BucketDriver`, abstract lib specific behaviour there and let the user choose which one to use as a parameter to `S3Storage`. By default we should keep boto for backward compatibility but using boto3 should be the matter of just turning on an option.

Then we should provide a `MinioStorage` that just inherits from `S3Storage`  and just enable the `Boto3BucketDriver` for convenience for new users that should just have to say _"how do I use depot with minio? Ah just use the MinioStorage"_.

**Comment by multiwave** [comment]
Just a quick update, the devil seems to be in the details, for example metadata doesn't really work with minio as of now (still investigating what the problem is). Also more code changes are needed than I posted - as soon as I have a working version I will get back to you.

I don't know yet how it can be integrated best into your current code. Using Inheritance will be quite a rewrite, as some things are fundamentally different in boto3 needing different init params for the helper classes `S3StoredFile` and `BucketDriver`.

**Comment by harshavardhana** [comment]
> Just a quick update, the devil seems to be in the details, for example metadata doesn't really work with minio as of now (still investigating what the problem is). Also more code changes are needed than I posted - as soon as I have a working version I will get back to you.

@multiwave can you let us know what do you mean by "metadata' doesn't really work? - Let us know can help with anything Minio specific here.

**Comment by vlcinsky** [comment]
Using `boto` is real problem as it became obsolete from AWS point of view.

There are far too many serious problems with `boto`.

`boto3` is a must.

**Comment by amol-** [comment]
https://github.com/amol-/depot/commit/27502ce7871513e8cd09deb20619fab58eb501f9 introduces an experimental support for boto3.

The codebase is still experimental and boto3 is far more messy than boto2 imho, so it will require some real testing to ensure it's as reliable as boto2 support.
