### ISSUE TITLE
Size of image / dimensions attribute/parameter ideas? 

### ISSUE THREAD

**Issue by rlam3** [amol-/depot#30]
I'm looking for a way to see where we could potentially add size of image / dimensions  into the metadata structure. Any ideas? Thanks!

For instance, upon opening or saving of the file to s3. I'd like to save the image width and height to the metadata automatically.

Also how would one go about doing the above and distinguish between the thumbnail and actual image?

**Comment by rlam3** [comment]
Using upload_type seems to be working with this issue as a workaround/fix

However, how are we able to update the json meta data? I saw something like _thaw and _frozen. because I'm using a sqlalchemy orm, could we use those to update the meta data? If not, what is the best way to update the data without having to reupload?

Also, I saw _apply_filters in interfaces.py. Is it possible to add filters/update filters and the backend via this after there has been a POST/creation of an object?

```python
        content = utils.file_from_content(content)
        # import pdb; pdb.set_trace()
        uploaded_image = Image.open(content)

        self['width'] = uploaded_image.width
        self['height'] = uploaded_image.height
```

**Comment by amol-** [comment]
uhm, you can just set values to `self`  during `process_content` method.

See https://github.com/amol-/depot/blob/master/depot/fields/specialized/image.py for an example.
It stores `thumb_path`  across the original image itself.

**Comment by rlam3** [comment]
@amol- Thanks for your reply. Was wondering if you had any insight on how to restore s3 files that have been deleted.

**Comment by amol-** [comment]
@rlam3 unless you have Versioning enabled ( http://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html ) there is no way I'm aware of.
