### ISSUE TITLE
SQLAlchemy integration does not work for polymorphic subtypes

### ISSUE THREAD

**Issue by href** [amol-/depot#33]
I work with [polymorphic subtypes](http://docs.sqlalchemy.org/en/latest/orm/inheritance.html#) in my application. While adding an UploadedFileField to the base class works, using the same field on the subclass will not work. The necessary functions of the mutation tracker are never called in this case.

[The problem seems to be this line.](https://github.com/amol-/depot/blob/6f3587e/depot/fields/sqlalchemy.py#L92)

Imho `propagate=True` should be used, to subscribe to all set events events - not just the events of the base class. I would imagine there are other inheritance scenarios that won't work because of this, but I only know for sure about my case.

[See also the docs about the the propagate keyword](http://docs.sqlalchemy.org/en/latest/orm/events.html#sqlalchemy.orm.events.AttributeEvents.params.propagate)

**Comment by href** [comment]
Can help somehow to get this fixed? I'm currently monkey-patching this on my end and it works in production without a hitch. Or is there some disagreement about my proposal?

**Comment by amol-** [comment]
Sorry, I just didn't have time to check the issue so far. 
Using `propagate=True` usually leads to the desired behaviour, but as DEPOT is now used on production by a few projects around I wanted to double check no unexpected behaviour arises.

I'll try to invest the time this weekend to install some of the few projects I know around using DEPOT and check they continue to work as expected with the change

**Comment by href** [comment]
> If you want to submit the pull request to add the option I'll gladly accept it, so I can just switch to that branch to do my tests and merge it in case they succeed :)

We have a deal ;).

I'll make sure to send a PR your way. Maybe I can even add a failing test.

**Comment by href** [comment]
I added the PR with a single test. Though it would be better (but a bit beyond the scope of this issue), to parameterise the tests and have the added Confidential class run through all the tests the Document class runs through.

Not sure how to do that nicely though, since I'm more used to py.test.
