### ISSUE TITLE
Sqlalchemy + S3 boto signature mismatch

### ISSUE THREAD

**Issue by sherzberg** [amol-/depot#4]
I have a flask app setup with sqlalchemy and am getting a boto signature mistmatch error. I have whittled the error down to the fact that following http://depot.readthedocs.org/en/latest/database.html#attaching-to-models setup, there is no default filename present for your call to set x-depot-filename in the __save_file method call in the awss3.py

Do I just need a custom sqlalchemy file field to set a filename?

**Comment by amol-** [comment]
I suppose that if you are missing the filename you are using something which is not a file (StringIO/ByteIO or similar) as for files themselves the filename is correctly preserved ( as tested by https://github.com/amol-/depot/blob/master/tests/test_fields_sqlalchemy.py#L63 ).

In such case the issue can probably be resolved by using `FileIntent` which will properly provide the filename and content_type: http://depot.readthedocs.org/en/latest/userguide.html#storing-data-as-files
