### ISSUE TITLE
Any example for django?

### ISSUE THREAD

**Issue by adriancarayol** [amol-/depot#43]
Is there any example where to configure the middleware (DepotManager.make_middleware(...), to use **public_url**) for django?

Thanks.

**Comment by amol-** [comment]
I'll create a pull request to provide one this weekend, will appreciate review from any django expert to ensure there aren't simpler ways to integrate it.

**Comment by amol-** [comment]
https://github.com/amol-/depot/pull/44 provides an example with django. I tried to keep it as small as possible to only showcase depot related code.

**Comment by adriancarayol** [comment]
Thank you so much, great work!
