### ISSUE TITLE
file_id generation customization

### ISSUE THREAD

**Issue by glibersat** [amol-/depot#5]
Hi,

First, thanks for this awesome library, it fits almost everything I need except one use case.

I have a mixed tree of static and dynamic files:

```
http://ex.com/x/y/z1 can be a dynamic object (my logic here)
http://ex.com/x/y/z2 can be a static picture (static serving using filedepot lookup)
```

Therefore, I need to lookup the static files by their request path (eg. /x/y/z2 --their actual URI ID). 
When using `create()`, `file_id` is generated by an arbitrary uuid, there I can't use `get()` to look up by their URI ID.
Would it be possible to allow overriding the way `file_id` is generated so i could compute it using the URI ?

Thanks,

Guillaume

**Comment by amol-** [comment]
Allowing custom file ids in DEPOT is not too hard (apart from GridFS backend which uses ObjectIDs) the core issue is that various parts of DEPOT require that the file id is always unique for each file instance.

For example the SQLAlchemy transaction integration works because when storing the file a new file_id is generated (as the old "version" of the file is still existing until the transaction is committed), so in your case each file would require a different url each time is changed. I'm not sure this is something easy to handle for users, suppose someone provides a custom ids generation that generates the same id (url) for the same file even when the file content changes, in that case it will lead to unpredictable behaviours when using SQLA/Ming integration.

**Comment by glibersat** [comment]
You're right, I need to keep the same URI if a resource is updated, which would mean reusing the same ID for a different file content. I've considered adding an indirection on my side but that requires to hit the database before serving the file, which is kind of a pity.

Would it be acceptable to imagine having an ID ('a revision id') and another identifier that reflects where the file is used? For a django model, it could be the ID associated with the instance it's linked with for example. In my case, that would be the URI.

This way, it doesn't break the unique ID mechanism for transaction but can still be used to look up files attached to a given object. I'm not aware of all the backends, but the two you have cited, I can easily imagine an implementation:
 - file: "objectid/versionid"
 - SQL: id + an indexed column of the "objectid"

I'd be happy to contribute to DEPOT if you feel this is right.

Thanks!

**Comment by iurisilvio** [comment]
I have a similar use case.

I want to use S3 to store lots of files. It is not a good thing to do it with only one bucket. I want to add the file to a subdirectory, maybe something like this:

object_id = abcd-1234-5678
path = /a/b/abcd-1234-5678

Another idea to separate my objects in buckets is with YYYY/mm:

path = /2015/08/abcd-1234-5678

**Comment by amol-** [comment]
@iurisilvio You can store different files to different buckets using multiple storages, see https://github.com/amol-/depot/issues/9 

Just configure multiple storages in depot and pass the storage that should be used to ``UploadedFile``. 
No need to use custom ids for that.

**Comment by iurisilvio** [comment]
Yes, I know it is possible, but this way I have to generate lots of storages.

It works for my example, but if I want buckets per hour (YYYY/mm/dd/HH), it consume too much memory just to maintain buckets in memory.

**Comment by vlcinsky** [comment]
@iurisilvio There is almost no limit in number of items stored in S3 bucket. It will perform well without any problem if you have large amount of items in one (virtual) bucket directory, one cannot compare it to what would happen on local file system which suffers a lot if number of items in one directory goes too far.

Personally I do not feel putting any logic into file_id is a good idea. One rule for modelling data tells, one shall not put any logic into object identifier.
