### ISSUE TITLE
Add filename and content_type args to DepotFileInfo constructor

### ISSUE THREAD

**Issue by iurisilvio** [amol-/depot#7]
The `process_content` method has `filename` and `content_type` args, but the `DepotFileInfo` call it with `process_content(content)`, because `DepotFileInfo` does not accept the other parameters.

I want to do this: `UploadedFile(content, filename="filename.txt")`

**Comment by amol-** [comment]
You can do that by using `cgi.FieldStorage` which is meant to store file, filename and content_type. Depot understands it and reuses the content_type and filename provided by the FieldStorage

**Comment by iurisilvio** [comment]
I understand. It works for me, but it is not straight forward. If this is the way to do it, it deserve some docs. :)

I did it with `StringIO`:

```
s = StringIO(content)
setattr(s, "name", "filename.txt")
```

The `FieldStorage` is a better solution. Thanks!

**Comment by amol-** [comment]
``FileIntent`` : http://depot.readthedocs.org/en/latest/userguide.html#storing-data-as-files should properly solve the need and provide an officially supported way to bind filename and additional data to a content.

**Comment by iurisilvio** [comment]
Thanks! It is a nice solution. I'll try it later.
