### ISSUE TITLE
Filename and last-modified metadata is lost when using S3

### ISSUE THREAD

**Issue by jackrosenthal** [amol-/depot#86]
Amazon's documentation on S3 states that [custom user-provided metadata must start with `x-amz-meta-`](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata).

However, depot appears to use the metadata headers `x-depot-filename` and `x-depot-modified`.  A conforming S3 service drops these headers.

**Comment by amol-** [comment]
Can you provide an example of a service dropping the headers? Depot has been using `x-depot-` since forever and it works fine on AWS S3, so it was never noticed for that reason.

**Comment by jackrosenthal** [comment]
It looks like I'm wrong here, and this was me over-thinking this one... looks like boto3 client automatically prefixes with `x-amz-meta-`:

```
$ s3cmd info s3://depot-test/250abbde-cec2-11ee-8cc1-0242475560d4
s3://depot-test/250abbde-cec2-11ee-8cc1-0242475560d4 (object):
   File size: 7
   Last mod:  Mon, 19 Feb 2024 00:59:33 GMT
   MIME type: text/plain
   Storage:   STANDARD
   MD5 sum:   9a0364b9e99bb480dd25e1f0284c8555
   SSE:       none
   Policy:    none
   CORS:      none
   ACL:       020eafdd6fd6: FULL_CONTROL
   ACL:       *anon*: READ
   URL:       http://depot-test.s3.us-west-004.backblazeb2.com/250abbde-cec2-11ee-8cc1-0242475560d4
   x-amz-meta-x-depot-modified: 2024-02-19 00:59:33
   x-amz-meta-x-depot-filename: test_file.txt
```

Apologies for the noise!
