### ISSUE TITLE
How do I use depot to specify which bucket to update/save an image to?

### ISSUE THREAD

**Issue by rlam3** [amol-/depot#9]
How do I use depot to specify which bucket to update/save an image to?

Currently I'm using sqlalchemy to as the orm and following your details my folder looks like 

This is what my folder looks like currently
```
/media
   /8404b4c7-2106-11e5-827f-685b358e848d
     /metadata.json
     /file
``

I want to separate out say for example, profile avatar and user images


Also, is there a way to get the size of the image that is stored within the folder/bucket?

**Comment by amol-** [comment]
If you want to split data to different locations you must use different storages.

Configure two storages with different names and then when storing the data in the SQLA column use UploadedFile with a specific depot_name parameter to then specify which storage the file should be saved to.

DEPOT storages are meant to work with different kind of backends and so do not support complex concepts like paths and directories as some backends do not support them.

**Comment by amol-** [comment]
Regarding the image file, if you mean the file size, you can get it from content_length property of the file.

If you want to have the image resolution, you can easily write a FileFilter which gets the image resolution and adds it as a property to your file. It will then be available when you .get() the file back. See http://depot.readthedocs.org/en/latest/database.html#attachment-filters

**Comment by rlam3** [comment]
Okay thanks. I got the file size from content_length. As for configuring two storages. I'm using flask and I'm doing the following inside my configuration file to register the depot extension.

```
# Depot List:
depot_list = [
    ('media',{'depot.storage_path': 'media/'}),
]
# Prevent DepotManager from reconfiguration error `RuntimeError: Depot default has already been configured`
for depot_name,depot_path in depot_list:
    if depot_name not in DepotManager._depots:
        DepotManager.configure(depot_name, depot_path)
if DepotManager._middleware is None:
    app.wsgi_app = DepotManager.make_middleware(app.wsgi_app)
```


I'm used to the traditional application factory style:
```
from flask.ext.sqlalchemy import SQLAlchemy
db = SQLAlchemy()
db.init_app(app)
```


If I'm understanding you correctly, I would need to add another depot storage to my depot list correct?
```
# Depot List:
depot_list = [
    ('media',{'depot.storage_path': 'media/'}),
    ('avatar',('depot.storage_path':'avatar/'))
]
```

My model looks like this currently:
```
avatar = db.Column(UploadedFileField)
```
How would I make the connection between this column to the avatar? I'm taking a look at the documentation filters and upload_type but can't make the connection on which ones to do. Do you mind showing me an example of what you're talking about?


Thanks!

**Comment by amol-** [comment]
When you assign DEPOT columns, depot actually automatically creates ``UploadedFile`` instances for you if you assign something which is not an ``UploadedFile``.

If you want to use a specific bucket, just create the ``UploadedFile`` instance yourself and pass the storage that should be used:

```
user.avatar = UploadedFile(image_file, 'avatar')
```

See http://depot.readthedocs.org/en/latest/api.html#depot.fields.sqlalchemy.UploadedFileField

**Comment by amol-** [comment]
Releasing 0.1.0 which allows setting storage on columns
